### PR TITLE
api of ipc

### PR DESCRIPTION
**Pull request by dankilman**

### CODE REVIEW

**Comment by eMPee584** [comment]
> _No description provided._

Yeah indeed 😅 ..
would this allow adding jobs on runtime? because `mp.add()` after `mp.run()` doesn't seem to work (duh) ..

**Comment by dankilman** [comment]
`mp.run` is just a thin wrapper on top of `mp.run_async`.
If you run your code in an async event loop, you can use `run_async` instead and add commands afterwards to your hearts content. You only need to make sure to call `mp.cleanup()` when leaving so the terminal is properly restored as this is one thing `run` does that `run_async` doesn't

**Comment by dankilman** [comment]
you can also `run` in main thread and `add` in other threads (passing the `thread_safe=True` flag)

**Comment by dankilman** [comment]
This PR is mostly about doing these things from a shell scripts like the example in the README

**Comment by eMPee584** [comment]
.. 
> you can also `run` in main thread and `add` in other threads (passing the `thread_safe=True` flag)
mmh thanks .. may sound trivial to you but as a python noob, I would love to see a minimal example.. but hope I'll eventually figure it out, just wanted to mention that 😅

**Comment by dankilman** [comment]
Presumably you are running things concurrently somehow, otherwise where would you add the jobs during runtime?
If you elaborate a little bit about where and how you want to use multiplex, I'll be happy to give a more concrete example.

**Comment by eMPee584** [comment]
Hey, thanks for your reply and sorry for the random latency.. had the ambition to "finish this first" but here's the script (draft state) where i wanted to try `multiplex`:

```
#!/usr/bin/python3
""" Auto-burn live-usb sticks on hot-plug. """

import datetime
import os
import subprocess
import time

import dialog
import humanize
import rich.console
import pyudev

udev = pyudev.Context()
monitor = pyudev.Monitor.from_netlink(udev)
monitor.filter_by(subsystem = 'block', device_type = 'disk')

def log_udev_event(dev):
    # log event type + device details (status, uptime, properties & attributes)
    print(f"dev.action={dev.action} {dev} {dev.is_initialized}"
          f" {dev.properties['USEC_INITIALIZED']} PROPS={list(dev.properties)}"
          f" ATTRS={list(dev.attributes.available_attributes)}")

def is_removable_device_ready(dev):
    # only proceed when a removable device has been added and initialized
    return (dev.action == 'add' and dev.is_initialized
            and 'removable' in dev.attributes.available_attributes
            and dev.attributes.asbool('removable'))

def parse_device_info(dev):
    """Function that is called for every device event."""

    return {
        # Gather medium info
        'path': dev.properties['DEVNAME'],
        'vendor': dev.properties['ID_VENDOR'],
        'device_type': dev.device_type,
        'model': dev.properties['ID_MODEL'],
        'serial': dev.properties['ID_SERIAL_SHORT'],
        'fslabel': dev.properties.get('ID_FS_LABEL'),
        'fstype': dev.properties.get('ID_FS_TYPE'),
        'size': dev.attributes.asint('size') * 512
        }

def log_device_info(dev, d):
    with open('/tmp/zram/stick.log', 'a+') as log_file:
        print(f"{dev.action} {d['path']} {d['vendor']} {d['model']}"
              f" {d['serial'][:10]} {humanize.naturalsize(d['size'])}"
              f" / {humanize.naturalsize(d['size'], binary = True)}"
              f" {d['device_type']} '{d['fslabel']}' '{d['fstype']}' at"
              f" {datetime.datetime.now()}", file = log_file)

        # List parent device chain
        #print(*list(dev.ancestors), sep='\n')
        #for parent in list(dev.ancestors)[3:-2]:
            #print(parent.attributes.get('product'))

def invoke_script(dev):
    """Invokes classic stick installation script with preset parameters."""

    if not is_removable_device_ready(dev):
        return
    d = parse_device_info(dev)
    log_device_info(dev, d)

    script = "scripts/stick-install"
    iso = "artifacts/OSEG-Makerstick_1771j_Xfce_buster-amd64.hybrid.iso"
    variant = "Makerstick.hotfix_1771j"
    fat32_partition_size = "2500"

    print(f"Invoking '{script} {d['path']} {iso} {variant} {fat32_partition_size}' now")
    subprocess.Popen(['/bin/sh', '-xc', f'echo sleeping 4 seconds for {d.path};'
                     f' sleep 4s; echo done for {d.path}'],
                     start_new_session = True)
    #subprocess.Popen([script, d.path, iso, variant, fat32_partition_size],
                     #start_new_session = True)

def invoke_bmaptool(dev):
    """Burn distribution image with bmaptool."""

    #log_udev_event(dev)
    if not is_removable_device_ready(dev):
        return
    d = parse_device_info(dev)
    log_device_info(dev, d)

    print(f"Device {d['path']} inserted ({d['vendor']} {d['model']} {d['serial'][:10]},"
          f" {humanize.naturalsize(d['size'])}"
          f" / {humanize.naturalsize(d['size'], binary = True)})")

    print(f"Invoking 'bmaptool copy /mnt/stix/schulstick-DD-Plauen.img {d['path']}' now")
    #subprocess.Popen(["/bin/time", "bmaptool", "copy",
                      #"/mnt/stix/schulstick-DD-Plauen.img", d.path],
                     #start_new_session = True)

def invoke_hotfix(dev):
    """Apply persistence hotfix for quickly rolling out post-ISO hacks."""

    if not is_removable_device_ready(dev):
        return
    d = parse_device_info(dev)
    log_device_info(dev, d)

    #subprocess.Popen(['/bin/sh', '-xc',
                      #'cd /mnt/stix/fsfw-dresden-usb-stick/variants.install/hotfix_1713w.no-psd'
                     #f' && sh install-hooks/copy_configs_to_persistence.sh {d.path}3'
                     #f' && echo hotfixed {d.path}'], start_new_session = True)

def main():
    # pylint: disable=anomalous-backslash-in-string
    """Main function."""
    con = rich.console.Console()
    tui = dialog.Dialog()
    tui.add_persistent_args(['--colors'])
    tui_retval, tui_tag = tui.menu('Please choose operation mode:', width = 80,
                          choices = [('SCRIPT', 'Execute script with preset parameters'),
                                     ('BMAPTOOL', '\Zb\Zr\Z6bmaptool copy\Zn an image file'),
                                     ('HOTFIX', 'Hotfix stick issues post-iso')])
    os.system('clear')
    print(f"dialog.menu() returned ({tui_retval}, {tui_tag})")
    if tui_retval == tui.OK:
        if tui_tag == 'SCRIPT':
            callback_handler = invoke_script
        elif tui_tag == 'BMAPTOOL':
            callback_handler = invoke_bmaptool
        elif tui_tag == 'HOTFIX':
            callback_handler = invoke_hotfix
        else:
            print("How tf did you end up here.")
            callback_handler = print

        observer = pyudev.MonitorObserver(monitor, callback = callback_handler)
        observer.start()

        con.print(f"[bold cyan]Autoburn activated with {callback_handler}[/]")
        con.input("Press [bold][ENTER][/] to [red]exit[/]..")
        print("observer stopped")
        time.sleep(0.5)
        os.system('clear')
    else:
        print("Cancelled. Goodbye.")


if __name__ == '__main__':
    main()
```

As you can see, every time a USB flash drive is plugged, a shell command is to be triggered and monitored. Any hints very welcome!

**Comment by dankilman** [comment]
If I understood your intent correctly, this is a mocked up version that should get you going
```python
import random
import time
import threading

import multiplex


class MonitorObserver(threading.Thread):
    def __init__(self, callback):
        super().__init__(daemon=True)
        self.callback = callback
        
    def run(self):
        while True:
            self.callback()
            time.sleep(10)


def handle_it(mp):
    something = random.randint(10000, 99999) 
    mp.add(
        multiplex.Process(
            [
                '/bin/sh', 
                '-c',
                f'echo sleeping 4 seconds for {something}; sleep 4; echo done for {something}',
            ],
        )
    )


def main():
    mp = multiplex.Multiplex()
    observer = MonitorObserver(callback=lambda: handle_it(mp))
    observer.start()
    mp.run()


if __name__ == '__main__':
    main()
```

the `multiplex.Process` is similar to just passing an `str` with the command but differs in that the `str` will use `asyncio.subprocess.create_subprocess_shell` and the latter, if a `list` is provided will use 
`asyncio.subprocess.create_subprocess_exec`

https://github.com/dankilman/multiplex/blob/8c3179830e54cc9bc0f27fbb7bff75baa961d739/src/multiplex/iterator.py#L122

**Comment by eMPee584** [comment]
Ah cool, thanks, I can work from that I think 😅
First problem however:
`AttributeError: module 'multiplex' has no attribute 'Process'`

**Comment by eMPee584** [comment]
on 0.5.1, I probably need a newer version right

**Comment by eMPee584** [comment]
... ook, so got this working nicely, had to use a `venv` (1st time 😅) to get the newer multiplex version and also figure out the key bindings, these are easy to use even though toggling between the modes is a bit unintuitive. But I was able to make my originally intended TUI experience work just fine, thanks for this! 😃
hotplug-autorun-multiwrite_2022-04-26_11-27-29
output dumping is cool as well, even though I'm doing logging myself for the `live-stick-info` part of the script, will come in handy for the `stick-install`. #awesome

**Comment by dankilman** [comment]
This is great news! Thanks for letting me know 🙏 .

As an aside, you should be able to upgrade multiplex without venv (dep`ending on how it is installed initially), but getting acquainted with virtualenvs is recommended nonetheless, so pure gain!

Re toggling between modes, I agree it gets a little tricky. I'll be happy to hear suggestions for improvements there if you have any.

**Comment by eMPee584** [comment]
Well, using debian I'd rather not mess with the system package and I hadn't yet figured out how to easily bump a package and roll a new version, so venv was the easiest.
Don't have an improvement suggestion but once I have I'll get back 🌈😀

**Pull request merged**
